language: node_js
node_js:
  - lts/*

# Default distribution. If left commented out,
# Travis will upgrade distros as needed
# dist: xenial
# os: linux

# we have to do some extra setup to let travis use the newer version of postgres + postgis
before_install:
  - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/12/main/postgresql.conf
  - sudo cp /etc/postgresql/{10,12}/main/pg_hba.conf
  - sudo service postgresql stop
  - sudo service postgresql start 12

services:
  - postgresql

addons:
  apt:
    packages:
      # Ubuntu 16+ does not install this dependency by default, so we need to install it ourselves
      # Required for Cypress. https://docs.cypress.io/guides/guides/continuous-integration.html#Travis
      - libgconf-2-4
      - postgresql-12
      - postgresql-12-postgis-3
      - postgresql-12-postgis-3-scripts
  postgresql: "12"

env:
  global:
    - NODE_ENV=test
    - PELIAS_API_KEY=ge-iampelias

before_script:
  # Start the server and run it in background process
  - node index &

script:
  # Note: don't run `npm test` here directly, it's intended for local testing.
  - commitlint-travis
  - npm run db:create
  - sequelize db:migrate
  - npm run jest
  - npm run lint
  - npm run cypress:run

after_script:
  # Send coverage reports generated by jest to Codecov
  - bash <(curl -s https://codecov.io/bash)
  # after all tests finish running we need
  # to kill all background jobs (like "npm start &")
  - kill $(jobs -p) || true

cache:
  # Caches $HOME/.npm when npm ci is default script command
  # Caches node_modules in all other cases
  npm: true
  directories:
    # we also need to cache folder with Cypress binary
    - ~/.cache
