coverage:
  status:
    project:
      default:
        # Allow project coverage to decrease a little
        # We don't want to fail projects where minor changes
        # cause coverage to decrease slightly
        threshold: 1%
