name: Update translations

on:
  schedule:
    # Daily at a specific time (7:30 chosen arbitrarily)
    - cron: "30 7 * * *"
  workflow_dispatch:

jobs:
  translations:
    runs-on: ubuntu-latest
    env:
      TRANSIFEX_API_TOKEN: ${{ secrets.TRANSIFEX_API_TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    # Use the current LTS version of Node.js
    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install necessary dependencies
      run: npm install dotenv chalk
    - name: Download translations
      run: node ./bin/download_translations.js
    - name: Check status
      run: git status
